name: (Windows) CMake with vcpkg

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Bootstrap vcpkg
        run: ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.bat

      - name: Install vcpkg dependencies (manifest mode)
        run: ${{ github.workspace }}/vcpkg/vcpkg.exe install --x-install-root=${{ github.workspace }}/vcpkg_installed

      - name: Configure CMake project with vcpkg toolchain
        run: cmake -S ${{ github.workspace }}/cppscraper -B ${{ github.workspace }}/build `
          -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake `
          -DCMAKE_PREFIX_PATH="${{ github.workspace }}/vcpkg_installed/x64-windows"

      - name: Build with CMake
        run: cmake --build build --config ${{ matrix.build_type }}
